base_dir: results
data:
  batch_size: 32
  dataset_dir: ./data/
  graph_pkl_filename: ./helper_files/adj_mat_volume.pkl
  test_batch_size: 64
  val_batch_size: 64
log_level: INFO
model:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 12
  input_dim: 1
  l1_decay: 0
  max_diffusion_step: 1
  num_nodes: 150
  num_rnn_layers: 2
  output_dim: 1
  rnn_units: 64
  seq_len: 12
  use_curriculum_learning: true
train:
  base_lr: 0.01
  dropout: 0
  epoch: 64
  epochs: 300
  epsilon: 0.001
  global_step: 18655
  groundtruth_file: y_truth_GCGRNN_volume_150.csv
  log_dir: results
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  model_filename: ./best_model\models-462.8403-63427
  optimizer: adam
  patience: 50
  preds_file: GCGRNN_volume_150.csv
  steps: '[20]'
  test_every_n_epochs: 1
