base_dir: results
data:
  batch_size: 32
  dataset_dir: ./GC-GRNN-Preds-on-Inputs/
  graph_pkl_filename: ./GC-GRNN-Preds-on-Inputs/adj_mat_volume.pkl
  test_batch_size: 64
  val_batch_size: 64
log_level: INFO
model:
  cl_decay_steps: 2000
  horizon: 12
  input_dim: 1
  l1_decay: 0
  num_nodes: 150
  num_rnn_layers: 1
  output_dim: 1
  rnn_units: 128
  seq_len: 12
  use_curriculum_learning: true
train:
  base_lr: 0.01
  dropout: 0
  epoch: 0
  epochs: 300
  epsilon: 0.001
  global_step: 0
  groundtruth_file: y_truth_GCGRNN_volume_150.csv
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  model_filename: ./best_model\models-325.1414-29274
  optimizer: adam
  patience: 50
  preds_file: GCGRNN_volume_150.csv
  steps: '[20]'
  test_every_n_epochs: 1
